/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*******************************************************************************
 ******************  Includes
 ******************************************************************************/
#include <stdint.h>
#include "MPU_Driver.h"

void MemManage_Handler(void){
	uint32_t faultAddr;
	uint8_t faultStatus;
	MPU_GetErrorDetails(&faultAddr, &faultStatus);
	while(1);	//Debug loi
}

/*******************************************************************************
 ************************** Main
 ******************************************************************************/
int main(void)
{
	volatile uint8_t count = 0;

	//Config 2 Region
	MPU_RegionConfig_t region[] = {
			{0, 0x00000000, 31, MPU_MEM_STRONG_ORDER, MPU_ACCESS_FULL, 1}, 			//Region 0: Background
			{1, 0x20005000, 9, MPU_MEM_NORMAL_NONCACHE, MPU_ACCESS_READ_ONLY, 1}	//Region 1: Test
	};
	MPU_Config_t mpuConfig = {
			MPU_ENABLE_DEFAULT_MEM, MPU_DISABLE_IN_EXCEPTION, 1, region, 2
	};

	//Init MPU
	MPU_Init(&mpuConfig);

	//Test write into Region 1 (Read Only)
	volatile uint32_t* test_addr = (uint32_t*)0x20005000;
	*test_addr = 0x12345678; 		//Gay ra MemFault

	/*If have no fault, jump to while(1)*/
	while(1)
	{
		count ++;
	}
}
/*******************************************************************************
 **************************** EOF
 ******************************************************************************/
