/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define RCC_APB2ENR   (*((volatile unsigned int*)0x40021018))
//addr base cua RCC la 0x40021000
//addr offset cua APB2ENR la 0x18
//Cong vao thi duoc 0x40021018
#define GPIOC_CRH     (*((volatile unsigned int*)0x40011004))
//tuong tu voi addr base cua GPIO port C la 0x40011000
//addr offset cua GPIOx_CRH la 0x04
#define GPIOC_ODR     (*((volatile unsigned int*)0x4001100C))
//addr base cua GPIO port C la 0x40011000
//addr offset cua GPIOx_ODR la 0x0c
#define IOPCEN        (1 << 4)

void delay(uint32_t time) {
    while(t--);
}

int main(void) {
    RCC_APB2ENR |= IOPCEN;
    GPIOC_CRH &= ~(0xF << 20);
    GPIOC_CRH |=  (0x2 << 20);

    while (1) {
        GPIOC_ODR ^= (1 << 13);
        delay(1000000);
    }
}




