/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stdint.h"
#include "MPU.h"
#include "MPU_Config.h"
#include "MPU_Base.h"
#include "SCB_Base.h"
#include "Std_Type.h"
#include "MPU_Type.h"

#define T_REGION				(1)
#define T_ADDRESS 				(0x40000000UL)

//boolean t_bMpu_ErrorDetected = FALSE;
//MPU_ErrorDetailsType *t_Mpu_FaultDetails;

int a = 1;

void MemManage_Handler(void);
void HardFault_Handler(void);

static const MPU_RegionConfigType MPU_ModuleConfig_0_RegionConfig[2] =
	{
		/* Generate Code */
		/* Region Configuration 0 */
	    {
	        0U,
	        0UL,
	        4294967295UL,
	        MPU_MEM_STRONG_ORDER,
	        MPU_PRIV_RWX_UNPRIV_RWX,
	    },


		/* Region Configuration 1 */
	    {
	        1U,
	        0x4000000UL,
	        0x40000400UL,
	        MPU_MEM_NORMAL_IO_NO_CACHE,
			MPU_PRIV_RX_UNPRIV_RX,
	    }
	/* !Generate Code */
	};

	const MPU_ConfigType MPU_Config_0 =
	{
	        ((Bool_Type)FALSE),
	        ((Bool_Type)FALSE),
	        ((Bool_Type)FALSE),
	        2,
	        MPU_ModuleConfig_0_RegionConfig
	};

int main(void) {
	// Initialize MPU
	MPU_Init(&MPU_Config_0);

	// Test error: write into Region 1 (Read Only)
	volatile uint32_t* test_addr = (uint32_t*)0x40000000;
	*test_addr = 0xDEADBEEF; // Get HardFault
}

void MemManage_Handler(void){
	a = 2;
	while (1); // Debug error
//	t_bMpu_ErrorDetected = MPU_GetErrorDetails(&t_Mpu_FaultDetails);
}

void HardFault_Handler(void){
	a = 3;
	while (1); // Debug error
}

